### PR TITLE
Fix bugs, update README

### PR DESCRIPTION
**Pull request by mexisme**

### CODE REVIEW

**Comment by kuahyeow** [comment]
@mexisme I don't think anyone here is interested. Do you prefer taking it over ?

**Comment by mexisme** [comment]
Yup, I'm totally keen to own this, but I fixed this on PS [down-] time, so felt it should be owned by them.

**Comment by mexisme** [comment]
(I want to convert it to Rust and/or Go)

**Comment by kuahyeow** [comment]
@mexisme I have spoken to the appropriate people - They agree PS does not need this repo. We are going to remove this repo. Please clone this in the next 2 days ?

After you give me the go ahead, I will then remove this repo from `powershop/`

**Comment by mexisme** [comment]
Would it be easier to transfer ownership to me, instead?

**Comment by kuahyeow** [comment]
@mexisme Either's fine, but you have https://github.com/mexisme/git-cache currently present, which presents a transfer

**Comment by mogest** [comment]
Code you wrote at Powershop remains copyright Powershop, but we don't need to host it on our github account.  Your fork is ahead of the powershop one, so I think that all that's left to do is delete the powershop copy and we're done.

**Comment by kuahyeow** [comment]
Deleting...

**Pull request closed without merging**
